[build]
builder = "dockerfile"

[deploy]
startCommand = "npx next start -p $PORT -H 0.0.0.0"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
